#!/bin/sh
set -e
case "$1" in
  remove|upgrade|deconfigure)
    if systemctl is-active --quiet rpi-io-mcp.service; then
      systemctl stop rpi-io-mcp.service
    fi
    if systemctl is-enabled --quiet rpi-io-mcp.service; then
      systemctl disable rpi-io-mcp.service
    fi
    ;;
esac
